[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/YOUR_ACTUAL_SHEET_URL_HERE"

[email]
sender = "eggleston.jd@gmail.com"
password = "ncmz gael crnl swlb"
receiver = "eggleston.jd@gmail.com"
